urls:
  - name: "Google"
    url: "https://google.com"
  - name: "Yandex"
    url: "https://yandex.ru"
  - name: "GitHub"
    url: "https://github.com"
  - name: "Youtube"
    url: "https://youtube.com"
  - name: "VK"
    url: "https://vk.com"
  - name: "Telegram"
    url: "https://telegram.org"
  - name: "Instagram"
    url: "https://instagram.com"